package dukes.greeting;

import jakarta.persistence.*;

import java.util.UUID;

// Make Greeting a Jakarta Persistence Entity that is not Cacheable
@Entity(name = "Greeting")
@Cacheable(value = false)
public class Greeting {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "message")
    String message;

    public Greeting(String message) {
        this.id = id;
        this.message = message;
    }

    public Greeting() {
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
/**
     * Helpful documentation:
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/entity
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/cacheable
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/id
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/generatedvalue
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/generationtype
     */

    // Add a field called id as primary key. Use autogenerated UUIDs for the primary key
    // Add a field called message. Use String as type for the field

    // Getters and Setters
}
